apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginxapp
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginxapp
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  labels:
    app: nginxapp
spec:
  type: NodePort
  selector:
    app: nginxapp
  ports:
    - port: 443
      nodePort: 443
      protocol: TCP
      name: https
    - name: ssh
      port: 6666
      nodePort: 6666
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginxapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxapp
  template:
    metadata:
      labels:
        app: nginxapp
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: services/nginx
        imagePullPolicy: Never
        env:
        - name: SSH_USER
          value: admin
        - name: SSH_PASSWORD
          value: admin
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 6666
          name: ssh
        livenessProbe:
          tcpSocket:
            port: 6666
          initialDelaySeconds: 30
          periodSeconds: 15
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: nginx-svc
          servicePort: 80
